#!/bin/bash
x=$((1 + $RANDOM % 20))
i=0
r=0
echo $x

while [ $r -lt 3 ]
do
read i
((r++))
if [ $x -gt $i ]
then
echo "It should be greater than the inputting number",  
fi 

if [ $x -lt $i ]
then 
echo "It should be less than the inputting number"
fi

if [ $x -eq $i ]
then 
echo "number is found"
break
fi
done

