#!/bin/bash
if [[ $# -lt 1 || $# -gt 1 ]]
then 
  echo "Enter one command line argument"
  exit
fi
if [[ -d $1 ]]
then
  if [[ $1 = "." || $1 = ".." ]]
  then 
    set "$1/" "${@:1}"
  fi 
  ls -rt $1 > helper
  lcount=$(wc -l < helper)
  if [[ $1 = "./" ]]
  then
    for (( i=1; i<=lcount; i++ ))
    do
      f_or_d=$(sed "${i}q;d" helper)
      if [[ -d $1$f_or_d ]]
      then
        echo "$f_or_d    `ls $1$f_or_d | wc -l`"
      elif [[ -f $1$f_or_d && $f_or_d != "helper" ]]
      then
        echo "$f_or_d    `wc -c < $1$f_or_d`"
      elif [[ $f_or_d != "helper" ]]
      then  
        echo "$f_or_d   isn't file or directory"
      fi
    done
  else 
    for (( i=1; i<=lcount; i++ ))
    do
      f_or_d=$(sed "${i}q;d" helper)
      if [[ -d $1$f_or_d ]]
      then
        echo "$f_or_d    `ls $1$f_or_d | wc -l`"
      elif [[ -f $1$f_or_d ]]
      then
        echo "$f_or_d    `wc -c < $1$f_or_d`"
      else 
        echo "$f_or_d   isn't file or directory"
      fi
    done
  fi
else 
  echo "Entered command line argument isn't directory"
  exit
fi
rm helper
