#!/bin/bash

#File move in directory
 filenames=`ls`
   for eachfile in $filenames
   do
       DIR=${eachfile:0:4}
   
       if [ ! -d "$DIR" ]; then
           mkdir ${eachfile:0:4}
      fi
  
      mv $eachfile ./$DIR
  done


